# require GITREPO_ACCESS_TOKEN
#   add GitHub access token to Projects Secrets

name: git fetch pull request code

on:
  pull_request:
    branches:
      - '*'

jobs:
  build:
    runs-on: macOS-10.14
    timeout-minutes: 10

    strategy:
      matrix:
        node-version: [12.4.0]

    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: echo
        run: echo "${{ REG_REPO }}"
        env:
          REG_REPO: "pr_${{ GITHUB_REF }}"
      #- run: echo "//npm.pkg.github.com/:_authToken=${{ secrets.NPM_AUTH_TOKEN }}" > ~/.npmrc
      #- name: npm install
      #  run: npm install
      #- name: checkout
      #  run: git checkout -b pr_${{ GITHUB_REF }}
      #- name: fetch
      #  run: git pull origin ${{ GITHUB_REF }}

